POST http://104.198.225.231:3000/automation HTTP/1.1
content-type: application/json

{
    "illumination": false,
    "device": "IoT-001"
}

###

GET http://localhost:3000/automation?device=iot-001 HTTP/1.1