version: "2"
services:
  server:
    container_name: server-ace2
    restart: always
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - networkapi
  database:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - networkapi

networks:
  networkapi:
    driver: "bridge"
